baseURL = "https://sionwilliams.com/"
languageCode = "en-us"
title = "Sion Williams"
theme = "hello-friend-ng"

# 3rd Party

enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[params]
    author = { name = "Sion Williams" }
    copyright = "Created with â™¥ by <a href='/about/'>Sion Williams</a>. All content is the property of Sion Williams. This blog, its content, and opinions are my own."
    dateform = "Jan 2, 2006"
    dateformShort = "Jan 2"
    dateformNum = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04"
    customCSS = ["/css/bookshelf.css"]

    # Metadata mostly used in document's head
    description = "My technology and engineering blog"
    keywords = "homepage, blog"
    images = [""]

    # Set disableReadOtherPosts to true in order to hide the links to other posts.
    disableReadOtherPosts = false
    # Prefix of link to the git commit detail page. GitInfo must be enabled.
    # gitUrl = ""
    # Directory name of your blog content (default is `content/posts`)
    contentTypeName = "posts"
    # Default theme "light" or "dark"
    defaultTheme = "dark"
    mainSections = ["posts"]

    # Reading Time
    enableReadingTime = true

    # Sharing Buttons
    enableSharingButtons = true

    # Utterances Comments
    [params.utterances]
        repository = "willis7/sionwilliams_com"
        issueTerm  = "pathname"
        theme      = "github-dark"

    # Social icons
    [[params.social]]
        name = "X"
        url  = "https://x.com/DarthSionno"

    [[params.social]]
        name = "email"
        url  = "mailto:sionix.mail@gmail.com"

    [[params.social]]
        name = "github"
        url  = "https://github.com/willis7"

    [[params.social]]
        name = "linkedin"
        url  = "https://www.linkedin.com/in/sionwilliams/"

    [[params.social]]
        name = "stackoverflow"
        url  = "https://stackoverflow.com/users/410527/sion"
    [[params.social]]
        name = "gitlab"
        url  = "https://gitlab.com/willis7"
    [[params.social]]
        name = "twitch"
        url  = "https://www.twitch.tv/sionno"
    [[params.social]]
        name = "reddit"
        url  = "https://www.reddit.com/user/nocpu"


[languages]
    [languages.en]
        title = "Sion's Blog"
        subtitle = "Technology and things I care about"
        keywords = "devops, agile, technology"
        copyright = "aka Papa DevOps"
        readOtherPosts = "Read other posts"

    [languages.en.params.logo]
        logoText = "$ /path/to/knowledge/"
        logoHomeLink = "/"
        logoCursorPathname = true
        logoCursorColor = "#77ff33"

[markup]
  [markup.goldmark]  
    [markup.goldmark.renderer]
        unsafe = true

[menu]
    [[menu.main]]
        name ="Home"
        url = "/"
        weight = 1
    [[menu.main]]
        identifier = "about"
        name       = "About"
        url        = "about/"
        weight = 2
    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
        weight = 3
    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags"
        weight = 4
    [[menu.main]]
        identifier = "bookshelf"
        name = "Bookshelf"
        url = "/bookshelf"
        weight = 5
    [[menu.main]]
        identifier = "series"
        name = "Series"
        url = "/series"
        weight = 6

[taxonomies]
    category = "categories"
    tag = "tags"
    series   = "series"