baseurl = "https://sionwilliams.com/"
buildDrafts = false
buildFuture = false
# googleAnalytics = "UA-119190708-1" # Deprecated
# googleAnalytics = "G-XXXXXXXXXX" # TODO: Replace with your GA4 Measurement ID
